org: ckeller22
app: aws-widget-corp-sentiment-analysis
service: aws-widget-corp-sentiment-analysis

frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  runtime: python3.11
  environment:
    AWS_S3_BUCKET_NAME: widget-corp-sentiment-analysis-assets-${self:provider.stage}
    AWS_MODEL_FILE_NAME: sa_classifier.pickle
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::widget-corp-sentiment-analysis-assets-${self:provider.stage}/*
            - arn:aws:s3:::widget-corp-sentiment-analysis-assets-${self:provider.stage}

functions:
  analyze:
    handler: sentiment.analyze
    timeout: 180
    memorySize: 5000

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: widget-corp-sentiment-analysis-assets-${self:provider.stage}
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
  Outputs:
    AssetsBucketName:
      Description: Generated s3 bucket.
      Value: widget-corp-sentiment-analysis-assets-${self:provider.stage}

plugins:
  - serverless-s3-sync
  - serverless-python-requirements
custom:
  s3Sync:
    - bucketName: widget-corp-sentiment-analysis-assets-${self:provider.stage}
      localDir: assets
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: false
    useStaticCache: false
    usePipenv: false
