org: ckeller22
app: aws-widget-corp-sentiment-analysis
service: aws-widget-corp-sentiment-analysis

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
